### ISSUE TITLE
Schema validation error for pw.x calculation with `ELECTRONS.diagonalization = 'rmm-davidson'`

### ISSUE THREAD

**Issue by sphuber** [QEF/qeschemas#13]
When parsing a calculation with the input card containing
```
&ELECTRONS
diagonalization = 'rmm-davidson'
/
```
the schema validation throws the error
```
 | failed validating 'rmm-davidson' with XsdEnumerationFacets(['davidson', 'cg', 'ppcg', 'paro', 'rmm(-davidson){0,1}(-paro){01}']):
 | 
 | Reason: value must be one of ['davidson', 'cg', 'ppcg', 'paro', 'rmm(-davidson){0,1}(-paro){01}']
 | 
 | Schema:
 | 
 |   <enumeration xmlns="http://www.w3.org/2001/XMLSchema" value="davidson" />
 | 
 | Instance:
 | 
 |   <diagonalization>rmm-davidson</diagonalization>
 | 
 | Path: /{http://www.quantum-espresso.org/ns/qes/qes-1.0}espresso/input/electron_control/diagonalization
```
This is for the schema with date code `220601`.

This happens for both QE 7.0 and 7.1

**Comment by sphuber** [comment]
Seems that it may have been fixed in the commits 42ee3eb11fb5b2b49d94cb914c4594f455974d32 and 20ef69831ad4a668c093a0df052a029cf83ebcbf ?

**Comment by sphuber** [comment]
Question is what schema we should now use in `aiida-quantumespresso` for QE 7.0 and up? Currently, we are parsing the schema version in the `data-file-schema.xml` output file to determine which XML schema version we should use for parsing, but unfortunately, the version printed in the XML output is often not updated to the correct schema, and so we parse against the wrong schema. What would be the best approach here?

**Comment by pietrodelugas** [comment]
I am very sorry for this. 
In the meantime I have set up the unit testing for the schemas and the xml to avoid these problems. Should have done before.  
At the moment the best solution is probably that I leave the  buggy 220601 in the the `test schemas` and instead make the one in `previous_schemas` a copy to 220603 so that you don't have to change anything on your side.
