### ISSUE TITLE
relation to qexsd repository?

### ISSUE THREAD

**Issue by ltalirz** [QEF/qeschemas#7]
When searching for the XSD QE schema I first ended up on https://github.com/QEF/qexsd which [does contain schemas](https://github.com/QEF/qexsd/tree/master/qespresso/scheme) as well before @mbercx pointed out to me that he gets the schemas from the `qeschemas` repository.

Perhaps the relationship between these two repositories could be clarified in their READMEs?

**Comment by pietrodelugas** [comment]
Sorry @ltalirz for the long delay. 
I will archive qexsd which is an old repository, we moved to this new one.

**Comment by ltalirz** [comment]
Thanks Pietro!
